dotwryn scwrypts v5 refactor

diff --git a/scwrypts/dotwryn/desktop/xorg/screen-blank b/scwrypts/dotwryn/desktop/xorg/screen-blank
--- a/scwrypts/dotwryn/desktop/xorg/screen-blank
+++ b/scwrypts/dotwryn/desktop/xorg/screen-blank
@@ -1,51 +1,61 @@
 #!/bin/zsh
-use desktop/notify --group dotwryn
+#####################################################################
+
+use notify
 
 DEPENDENCIES+=(xset)
+
 #####################################################################
 
 MAIN() {
+	local SCWRYPTS_NOTIFICATION_ENGINES=(echo notify.desktop)
 	case $1 in
 		enable | disable | query | toggle ) ACTION="$1" ;;
 		* )
 			[ ! $1 ] && ACTION=toggle
-			echo $ACTION
+			echo ${ACTION}
 			;;
 	esac
 
-	[[ $ACTION =~ ^toggle$ ]] && {
+	[[ ${ACTION} =~ ^toggle$ ]] && {
 		xset -q | grep -qi 'prefer blanking: *no' \
 			&& ACTION='enable' || ACTION='disable'
 	}
 
-	[ ! $ACTION ] && NOTIFY_FAIL 1 "unknown screen blank action '$1'"
+	[ ${ACTION} ] \
+		|| notify.error "unknown screen blank action '$1'" \
+		|| return 1
 
-	case $ACTION in
+	case ${ACTION} in
 		enable ) : \
-			&& STATUS 'enabling screen blank' \
+			&& echo.status 'enabling screen blank' \
 			&& xset +dpms \
 			&& xset s blank \
 			&& xset s on \
-				&& NOTIFY_SUCCESS 'enabled screen blank' \
-				|| NOTIFY_FAIL 2 'error enabling screen blank'
+				&& notify.success 'enabled screen blank' \
+				|| notify.error   'error enabling screen blank' \
+				|| return 2
 			;;
 
 		disable ) : \
-			&& STATUS 'disabling screen blank' \
+			&& echo.status 'disabling screen blank' \
 			&& xset dpms 0 0 0 \
 			&& xset s noblank \
 			&& xset s off \
-				&& NOTIFY_SUCCESS 'disabled screen blank' \
-				|| NOTIFY_FAIL 2 'error disabling screen blank'
+				&& notify.success 'disabled screen blank' \
+				|| notify.error   'error disabling screen blank' \
+				|| return 2
 			;;
 
 		query )
 			xset -q | grep -qi 'prefer blanking: *no' \
 				&& CURRENT_STATE='disabled' || CURRENT_STATE='enabled'
 
-			[ ! $CURRENT_STATE ] && NOTIFY_FAIL 3 'unable to determine current setting'
+			[ ${CURRENT_STATE} ] \
+				|| notify.error 'unable to determine current setting' \
+				|| return 3
 
-			NOTIFY_SUCCESS "screen blank is currently \\033[0;34m$CURRENT_STATE"
+			notify.success "screen blank is currently $(utils.colors.print blue "${CURRENT_STATE}")"
 			;;
 	esac
 }
diff --git a/scwrypts/dotwryn/system/setup b/scwrypts/dotwryn/system/setup
--- a/scwrypts/dotwryn/system/setup
+++ b/scwrypts/dotwryn/system/setup
@@ -6,12 +6,42 @@ use system --group dotwryn
 #####################################################################
 
 USAGE__description='
-	sets up links to things like /etc/*.d/ configurations
-	or systemd services; requires root access
+	Set up symlinks to source-controlled config files, configure terminfo,
+	and complete other computer setup/maintenance tasks.
 '
+
+dotwryn.system.zshparse.dry-run.usage
 
 #####################################################################
 
 MAIN() {
-	dotwryn.system.setup
+	local FORWARD_ARGS=()
+	local PARSERS=(dotwryn.system.zshparse.dry-run)
+	eval "$(utils.parse.autosetup)"
+	##########################################
+
+	dotwryn.system.symlinks.setup ${FORWARD_ARGS[@]} \
+		|| ((ERRORS+=1))
+
+	dotwryn.system.terminfo.setup ${FORWARD_ARGS[@]} \
+		|| ((ERRORS+=1))
+
+	##########################################
+
+	case ${DRY_RUN} in
+		( true ) ;;
+		( false )
+			[[ ${ERRORS} -eq 0 ]] \
+				&& echo.success "successfully completed system setup" \
+				|| echo.error   "one or more errors encountered during setup (see above)" \
+				;
+			;;
+	esac
+}
+
+#####################################################################
+
+MAIN.parse() { return 0; }
+MAIN.parse.validate() {
+	[[ DRY_RUN =~ true ]] && FORWARD_ARGS+=(--dry-run)
 }
